<#
.SYNOPSIS
  Gumbel-Zero joint sweep: random-search over the self-play trainer's
  hyperparameter space AND the Gumbel MCTS search-shape knobs
  (cvisit/cscale/m), trained and screened via gauntlet-style rating against
  the fixed default screening pool.

.DESCRIPTION
  Draw list is generated by tools/gumbelzero_joint_sample.ps1's
  Get-GumbelZeroJointDraws (dot-sourced below), the single source of truth
  for the sampling -- this script never re-implements it. Random search
  (Bergstra & Bengio 2012, Docs/works-cited.md), not one-axis-at-a-time. See
  Docs/model-training-playbook.md.

  Each draw fixes 9 axes at once: 6 training axes (sims, lr, l2, replay
  capacity/warmup, batch size, open-plies) passed to train.exe gumbelzero,
  plus 3 search-shape axes (cvisit, cscale, m) that apply ONLY at the
  certification head gaz(sims=N,cvisit=C,cscale=S,m=M)@1 built in the roster
  phase -- the self-play generator does not read them (Gumbel-Zero always
  self-plays with the paper's own defaults; only serving-time search shape
  varies). A draw's `sims` value is used for BOTH generation and
  certification, per Docs/model-training-playbook.md's "Generator/search
  depth" guidance.

  Linear architecture, from-scratch init ONLY -- train.exe's gumbelzero
  subcommand has no --model-type/--mlp-hidden/--init flag (confirmed
  2026-08-17). MLP + a second init scheme is a follow-up round once trainer
  support exists, once this round's results are reviewed with the developer
  (same two-stage pattern as the earlier Pass-2 Round A -> Round B).

  1 seed per draw, 4 shared rungs (100/400/1500/4000 games) so every arm
  gets checkpointed at the SAME points and an interior optimum can't be
  missed by screening at only one rung.

  Rating is gauntlet-style against a FIXED, regime-diverse, Elo-spread pool
  (ranking/roster_screening_pool.txt, the project default for exactly this
  job -- Docs/ranking-workflow.md's "Default gauntlet pool") rather than
  rand@1 alone, which saturates and carries no signal among strong agents.
  Implemented as a pinned-fit cohort play (Docs/ranking-workflow.md Workflow
  A) rather than N separate `rank.exe gauntlet` invocations: strictly more
  informative for a GROUP of this size, because cohort-vs-cohort games also
  resolve the 404 checkpoints' ordering AMONG THEMSELVES, which N gauntlets
  cannot see, and it is one sharded batch play + one fit instead of 404
  sequential single-process launches. The working roster for this play is
  seeded from roster_screening_pool.txt (NOT the full ranking/roster.txt),
  so --cohort games are scoped to the 26-agent pool, not all ~170+ active
  agents.

    SCREEN  rank.exe rate --pin ranking/standings.tsv
            The screening pool is held at its current Elo and only the
            cohort is solved. Cannot dethrone anything (ratings are inputs).
    CERTIFY A plain unpinned refit, run deliberately as a LATER step once
            the checkpoints to keep have been chosen (ranking/CHAMPION.md
            rule 1). Not run by this script.

  Screening pool (-ScreenStore): cohort games go to their own store, never
  the permanent ladder.

.PARAMETER Workers
  Parallel training processes, and shards for the play phase.

.PARAMETER Phase
  all | train | roster | play | screen | export. Phases are resumable and
  idempotent.

.PARAMETER GamesPerPair
  Games per pair for the play phase (gauntlet-equivalent games/opponent).

.PARAMETER N
  Number of random draws (plus 1 fixed reference configuration). Must match
  what was reviewed via gumbelzero_joint_sample.ps1.

.PARAMETER SweepSeed
  Seed for the random draw. Default 8817, reviewed via
  gumbelzero_joint_sample.ps1 before this script ran.

.PARAMETER OnlyDraws
  Limit to the first K draws (in sampled order, REF first) -- for the
  1-arm timing check before committing to the full sweep. 0 = all.
#>
param(
    [int]$Workers = 12,
    [ValidateSet("all","train","roster","play","screen","export")]
    [string]$Phase = "all",
    [int]$GamesPerPair = 16,
    [int]$N = 100,
    [int]$SweepSeed = 8817,
    [int]$OnlyDraws = 0,
    [string]$ScreenStore = "ranking/matches_screen_gzjoint.jsonl",
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"
$Root       = Split-Path -Parent $PSScriptRoot
$TrainExe   = Join-Path $Root "train.exe"
$RankExe    = Join-Path $Root "rank.exe"
$SweepDir   = Join-Path $Root "models\sweep"
$Ledger     = Join-Path $SweepDir "gumbelzero_joint_study.csv"
$RosterOut  = Join-Path $Root "ranking\roster_gumbelzero_joint.txt"
$CohortOut  = Join-Path $Root "ranking\cohort_gumbelzero_joint.txt"
$BaseRoster = Join-Path $Root "ranking\roster_screening_pool.txt"
$Standings  = Join-Path $Root "ranking\standings.tsv"
$PinnedStandings = Join-Path $Root "ranking\standings_screen_gzjoint_pinned.tsv"
$ResultsOut = Join-Path $Root "plans\gumbel-mcts-joint-sweep-agents-5-violet-harbor.tsv"
$ResultsWideOut = Join-Path $Root "plans\gumbel-mcts-joint-sweep-agents-5-violet-harbor.wide.tsv"

# Shared across EVERY draw (the consistency rule): no draw gets finer or
# coarser resolution than another.
$SharedRungs = 100,400,1500,4000

# ---- Draw list: single source of truth is Get-GumbelZeroJointDraws ----
. (Join-Path $PSScriptRoot "gumbelzero_joint_sample.ps1")
$Draws = @(Get-GumbelZeroJointDraws -N $N -SweepSeed $SweepSeed)
if ($OnlyDraws -gt 0) { $Draws = @($Draws | Select-Object -First $OnlyDraws) }

# ---- Expand draws x seeds into training-run cells ----
# Slots 998.. (Round A/B own up to 997; see src/CLAUDE.md's slotFile() note).
$Cells = @()
$slot = 998
foreach ($row in $Draws) {
    $seed = if ($row.Draw -eq "REF") { 8801 } else { 8800 + [int]($row.Draw.Substring(1)) }
    $c = [ordered]@{
        Block = $row.Draw; Seed = $seed; Rungs = $SharedRungs
        Sims = [int]$row.Sims; Lr = $row.Lr; L2 = $row.L2
        ReplayCap = [int]$row.ReplayCap; ReplayWarm = [int]$row.ReplayWarm
        Batch = [int]$row.Batch; Open = [int]$row.Open
        Cvisit = [int]$row.Cvisit; Cscale = [int]$row.Cscale; M = [int]$row.M
    }
    $c.Slots = @()
    foreach ($r in $SharedRungs) { $c.Slots += $script:slot; $script:slot++ }
    $Cells += [PSCustomObject]$c
}

$totalAgents = ($Cells | ForEach-Object { $_.Slots.Count } | Measure-Object -Sum).Sum
Write-Host "Gumbel-Zero joint sweep: $($Draws.Count) draws (seed $SweepSeed) -> $($Cells.Count) training runs -> $totalAgents cohort agents (slots 998..$($slot-1))"

if (-not (Test-Path $SweepDir)) { New-Item -ItemType Directory -Path $SweepDir | Out-Null }
if (-not (Test-Path $Ledger)) {
    "block,seed,sims,lr,l2,replaycap,replaywarm,batch,open,cvisit,cscale,m,rung,slot,model" |
        Out-File -FilePath $Ledger -Encoding ascii
}
$done = @{}
Import-Csv $Ledger | ForEach-Object { $done["$($_.block)|$($_.seed)|$($_.rung)"] = $_ }

# ---- Phase: train ----
function RunTraining {
    $jobs = @()
    foreach ($c in $Cells) {
        $key = "$($c.Block)|$($c.Seed)|$($c.Rungs[-1])"
        if ($done.ContainsKey($key)) { Write-Host "  [skip] $($c.Block) seed $($c.Seed) already trained"; continue }
        $out = "models/sweep/gzj_$($c.Block)_s$($c.Seed)"
        $a = @("gumbelzero", "--out", $out,
               "--ckpt-at", ($c.Rungs -join ","),
               "--games", $c.Rungs[-1],
               "--sims", $c.Sims, "--lr", $c.Lr, "--l2", $c.L2,
               "--replay-capacity", $c.ReplayCap, "--replay-warmup", $c.ReplayWarm,
               "--batch-size", $c.Batch, "--open-plies", $c.Open,
               "--seed", $c.Seed, "--report-every", 0)
        Write-Host "  train $($c.Block) seed $($c.Seed): sims=$($c.Sims) lr=$($c.Lr) l2=$($c.L2) replay=$($c.ReplayCap)/$($c.ReplayWarm) batch=$($c.Batch) open=$($c.Open) | cert: cvisit=$($c.Cvisit) cscale=$($c.Cscale) m=$($c.M)"
        if ($DryRun) { continue }
        while (@($jobs | Where-Object { -not $_.HasExited }).Count -ge $Workers) { Start-Sleep -Milliseconds 400 }
        $jobs += Start-Process -FilePath $TrainExe -ArgumentList $a -PassThru -NoNewWindow `
                     -RedirectStandardOutput "$SweepDir\gzj_$($c.Block)_s$($c.Seed).log"
    }
    if (-not $DryRun) {
        Write-Host "  waiting for $(@($jobs | Where-Object { -not $_.HasExited }).Count) run(s)..."
        $jobs | ForEach-Object { $_.WaitForExit() }
    }

    # Publish each rung into its own slot file and record it.
    foreach ($c in $Cells) {
        $out = "models/sweep/gzj_$($c.Block)_s$($c.Seed)"
        for ($i = 0; $i -lt $c.Rungs.Count; $i++) {
            $rung = $c.Rungs[$i]; $sl = $c.Slots[$i]
            $src = Join-Path $Root "$($out)_g$rung.txt"
            $dst = Join-Path $SweepDir "slot$sl.txt"
            if (-not (Test-Path $src)) { Write-Warning "  missing rung $rung for $($c.Block) s$($c.Seed)"; continue }
            Copy-Item $src $dst -Force
            $key = "$($c.Block)|$($c.Seed)|$rung"
            if (-not $done.ContainsKey($key)) {
                "$($c.Block),$($c.Seed),$($c.Sims),$($c.Lr),$($c.L2),$($c.ReplayCap),$($c.ReplayWarm),$($c.Batch),$($c.Open),$($c.Cvisit),$($c.Cscale),$($c.M),$rung,$sl,$dst" |
                    Add-Content -Path $Ledger -Encoding Ascii
            }
        }
    }
}

# ---- Phase: roster ----
# Writes roster_gumbelzero_joint.txt (roster_screening_pool.txt plus the
# cohort) and cohort_gumbelzero_joint.txt (the id list --cohort reads). Each
# cohort agent is rated under gaz(sims=N,cvisit=C,cscale=S,m=M)@1 with N/C/S/M
# = the SAME values drawn for its training block.
function BuildRoster {
    $hashes = @{}
    & $RankExe check 2>&1 | Select-String 'models/sweep/slot(\d+)\.txt = ([0-9a-f]{8})' | ForEach-Object {
        $hashes[[int]$_.Matches[0].Groups[1].Value] = $_.Matches[0].Groups[2].Value
    }
    $lines = @(); $ids = @()
    foreach ($c in $Cells) {
        for ($i = 0; $i -lt $c.Rungs.Count; $i++) {
            $sl = $c.Slots[$i]
            if (-not $hashes.ContainsKey($sl)) { Write-Warning "  no hash for slot $sl (not trained?)"; continue }
            $id = "gaz(sims=$($c.Sims),cvisit=$($c.Cvisit),cscale=$($c.Cscale),m=$($c.M))@1.learned(s$sl,$($hashes[$sl]))@1"
            $lines += "on $id"; $ids += $id
        }
    }
    $marker = "# ---- Gumbel-Zero joint sweep cohort ($($ids.Count) agents), added $(Get-Date -Format yyyy-MM-dd) ----"
    Get-Content $BaseRoster | Out-File -FilePath $RosterOut -Encoding ascii
    "" | Add-Content -Path $RosterOut -Encoding ascii
    $marker | Add-Content -Path $RosterOut -Encoding ascii
    $lines | Add-Content -Path $RosterOut -Encoding ascii

    # The short-form learned(s<slot>,<hash>) spelling above omits the arch
    # descriptor (regime/type/shape) that a canonical roster line requires --
    # `rank.exe canon` rewrites every id via rankAgentId (the same re-derive
    # rankAgentFromId's own canonical check uses), leaving state/comments/
    # blank lines untouched, so this can never drift from what the parser
    # actually accepts.
    $canonLines = & $RankExe canon --roster $RosterOut
    $canonLines | Out-File -FilePath $RosterOut -Encoding ascii

    # Cohort list = the canonicalized "on <id>" lines after the marker.
    $afterMarker = $false
    $canonLines | ForEach-Object {
        if ($_ -eq $marker) { $script:afterMarker = $true; return }
        if ($script:afterMarker -and $_ -match '^on\s+(\S.*)$') { $Matches[1] }
    } | Out-File -FilePath $CohortOut -Encoding ascii

    Write-Host "  roster -> $RosterOut ($($ids.Count) cohort agents appended, base = $BaseRoster)"
    Write-Host "  cohort -> $CohortOut"
    & $RankExe check --roster $RosterOut 2>&1 | Select-String -NotMatch '^model hash' | Select-Object -Last 4
}

# ---- Phase: play ----
# Pool-only gauntlet games (rank.exe gauntlet), NOT play --cohort: a pinned
# cohort play also schedules cohort-vs-cohort games, which is quadratic in
# cohort size (404 checkpoints -> 1.3M internal games, ~48hr measured
# 2026-08-17/18 in the 1-arm timing check) -- decided against by the
# developer in favor of true gauntlet semantics (each checkpoint vs only the
# 27-agent pool, ~175K games, ~5.6hr). Each checkpoint's Elo then comes
# purely from its record against the fixed pool; checkpoint-vs-checkpoint
# ordering is left to the pinned fit's transitivity in the screen phase, not
# played directly.
#
# Workers run in PARALLEL PROCESSES, each writing its OWN shard store file
# (never multiple processes appending one shared file -- unlike a single
# ofstream append, concurrent multi-process appends to one file are not
# guaranteed atomic on Windows/NTFS and risk interleaved/corrupt JSONL lines,
# the same class of risk run_rank.ps1's shard-then-merge pattern avoids).
# Merged into $ScreenStore only after every worker exits cleanly.
function PlayCohort {
    $ids = Get-Content $CohortOut | Where-Object { $_.Trim() -ne "" }
    Write-Host "  gauntlet-playing $($ids.Count) checkpoints at $GamesPerPair games/opponent vs roster_screening_pool.txt, $Workers shards"
    Write-Host "  store: $ScreenStore (screening pool, NOT the permanent ladder)"

    $shardFiles = @()
    # Round-robin partition into $Workers shards.
    $buckets = New-Object 'System.Collections.Generic.List[System.Collections.Generic.List[string]]'
    for ($w = 0; $w -lt $Workers; $w++) { $buckets.Add((New-Object 'System.Collections.Generic.List[string]')) }
    for ($i = 0; $i -lt $ids.Count; $i++) { $buckets[$i % $Workers].Add($ids[$i]) }

    $jobs = @()
    for ($w = 0; $w -lt $Workers; $w++) {
        if ($buckets[$w].Count -eq 0) { continue }
        $shardStore = "$ScreenStore.$w"
        $shardFiles += $shardStore
        $bat = Join-Path $SweepDir "gzj_play_worker$w.bat"
        $lines = @("@echo off")
        foreach ($id in $buckets[$w]) {
            $lines += "`"$RankExe`" gauntlet --roster `"$BaseRoster`" --in `"$shardStore`" --id `"$id`" --games $GamesPerPair --keep"
            $lines += "if errorlevel 1 exit /b 1"
        }
        $lines += "exit /b 0"
        $lines | Out-File -FilePath $bat -Encoding ascii
        if ($DryRun) { continue }
        $p = Start-Process -FilePath "cmd.exe" -ArgumentList "/c", "`"$bat`"" -PassThru -NoNewWindow `
                 -RedirectStandardOutput "$SweepDir\gzj_play_worker$w.log"
        # Touch .Handle immediately -- a documented Start-Process -PassThru
        # quirk where .ExitCode reads back empty/null after WaitForExit()
        # unless the process Handle was accessed right after it started
        # (hit 2026-08-18: all 4 timing-check shards printed correct
        # results but were flagged "failed" from a null ExitCode).
        [void]$p.Handle
        $jobs += $p
    }
    if (-not $DryRun) {
        Write-Host "  waiting for $($jobs.Count) shard(s)..."
        $jobs | ForEach-Object { $_.WaitForExit() }
        $bad = $jobs | Where-Object { $_.ExitCode -ne 0 }
        if ($bad) { throw "  $($bad.Count) gauntlet shard(s) exited non-zero; store NOT merged, inspect gzj_play_worker*.log" }
        foreach ($sf in $shardFiles) {
            if (Test-Path $sf) {
                Get-Content $sf | Add-Content -Path $ScreenStore -Encoding Ascii
                Remove-Item $sf -Force
            }
        }
        Write-Host "  merged $($shardFiles.Count) shard(s) -> $ScreenStore"
    }
}

# ---- Phase: screen ----
function ScreenCohort {
    Write-Host "  pinned fit over $ScreenStore (screening pool frozen at ranking/standings.tsv)"
    & $RankExe rate --roster $RosterOut --in $ScreenStore --pin $Standings
    Write-Host ""
    Write-Host "Cohort results are in ranking/standings_screen_gzjoint_pinned.tsv (canonical files untouched)."
    Write-Host "CERTIFICATION is a separate, deliberate step, not run by this script."
}

# ---- Phase: export ----
# Merges the training ledger against the pinned screening fit into one flat
# "agents trained x results" table (tools/export_cohort_results.ps1, a
# generic tool reused across cohort studies -- see tools/CLAUDE.md). This is
# the standard last step of any cohort study here, not specific to this one.
function ExportResults {
    $notes = @(
        "Gumbel-Zero joint training x search-shape sweep (plans/gumbel-mcts-results-5-violet-harbor.md). One row per checkpoint (404 total: 101 draws x 4 rungs).",
        "cvisit/cscale/m columns are RATING-time search shape only (the gaz(...) serving head). Training self-play never reads them: ml_gumbelzero.cpp calls",
        "gumbelSearch() directly and never touches g_gumbelCVisit/g_gumbelCScale/g_gumbelRootM, so every row's actual self-play search shape is the fixed engine",
        "default (cvisit=50, cscale=1.0, m=16), regardless of the swept cvisit/cscale/m values below.",
        "elo/games/cpu_ms_move/playstyle columns are from a PINNED screening fit against ranking/roster_screening_pool.txt (Docs/ranking-workflow.md Workflow A):",
        "screening only, not certification -- see the results doc's Caveats section before treating any single row's Elo as a reliable ranking."
    )
    & (Join-Path $PSScriptRoot "export_cohort_results.ps1") `
        -Ledger $Ledger `
        -PinnedStandings $PinnedStandings `
        -Out $ResultsOut `
        -HeaderComment $notes `
        -GroupBy block,seed -WideBy rung -WideOut $ResultsWideOut
}

switch ($Phase) {
    "train"  { RunTraining }
    "roster" { BuildRoster }
    "play"   { PlayCohort }
    "screen" { ScreenCohort }
    "export" { ExportResults }
    "all"    { RunTraining; BuildRoster; PlayCohort; ScreenCohort; ExportResults }
}
