<#
.SYNOPSIS
  Gumbel-Zero architecture sweep: random-search over mlp/conv model
  architecture, jointly with the self-play trainer's hyperparameter space
  and the Gumbel MCTS search-shape knobs (cvisit/cscale/m), trained and
  screened via gauntlet-style rating against the fixed default screening
  pool.

.DESCRIPTION
  Follow-up round to the joint sweep (gumbelzero_joint_study.ps1,
  plans/gumbel-mcts-results-5-violet-harbor.md), which was linear-only,
  from-scratch-only because train.exe's gumbelzero subcommand had no
  --model-type/--mlp-hidden/--conv-channels flag when that study launched.
  Those flags now exist, so this study covers the deferred architecture
  axis. Linear is NOT redrawn here -- results-5 already covers it (404
  checkpoints); this study's cohort is mlp and conv only.

  Draw list is generated by tools/gumbelzero_arch_sample.ps1's
  Get-GumbelZeroArchDraws (dot-sourced below), the single source of truth
  for the sampling -- this script never re-implements it. Random search
  (Bergstra & Bengio 2012, Docs/works-cited.md), not one-axis-at-a-time. See
  Docs/model-training-playbook.md.

  Each draw fixes 11 axes at once: model type (mlp/conv), the matching
  architecture axis (--mlp-hidden for mlp, --conv-channels for conv, conv's
  own --mlp-hidden FC-head axis held fixed empty this round), 6 training
  axes (sims, lr, l2, replay capacity/warmup, batch size, open-plies) passed
  to train.exe gumbelzero, plus 3 search-shape axes (cvisit, cscale, m) that
  apply ONLY at the certification head gaz(sims=N,cvisit=C,cscale=S,m=M)@1
  built in the roster phase -- the self-play generator does not read them.
  A draw's `sims` value is used for BOTH generation and certification, per
  Docs/model-training-playbook.md's "Generator/search depth" guidance.

  1 seed per draw (developer-confirmed breadth-over-reliability trade for
  this round, same choice results-5 made), 4 shared rungs (100/400/1500/
  4000 games) so every arm gets checkpointed at the SAME points and an
  interior optimum can't be missed by screening at only one rung.

  Rating is gauntlet-style against the FIXED, regime-diverse, Elo-spread
  screening pool (ranking/roster_screening_pool.txt, Docs/ranking-
  workflow.md's "Default gauntlet pool"), implemented as a pinned-fit
  cohort play (Workflow A) exactly as results-5 did -- see that study's own
  header comment (gumbelzero_joint_study.ps1) for why pool-only gauntlet
  beats cohort-vs-cohort play at this cohort size.

    SCREEN  rank.exe rate --pin ranking/standings.tsv
            The screening pool is held at its current Elo and only the
            cohort is solved. Cannot dethrone anything (ratings are inputs).
    CERTIFY A plain unpinned refit, run deliberately as a LATER step once
            the checkpoints to keep have been chosen (ranking/CHAMPION.md
            rule 1). Not run by this script.

.PARAMETER Workers
  Parallel training processes, and shards for the play phase.

.PARAMETER Phase
  all | train | roster | play | screen | export. Phases are resumable and
  idempotent.

.PARAMETER GamesPerPair
  Games per pair for the play phase (gauntlet-equivalent games/opponent).

.PARAMETER N
  Number of random draws PER ARCHITECTURE (plus 1 fixed reference per
  architecture). Must match what was reviewed via gumbelzero_arch_sample.ps1.

.PARAMETER SweepSeed
  Seed for the random draw. Default 8917, reviewed via
  gumbelzero_arch_sample.ps1 before this script ran.

.PARAMETER OnlyDraws
  Limit to the first K draws (in sampled order, REF_MLP/REF_CONV first) --
  for the 1-arm-per-architecture timing check before committing to the full
  sweep. 0 = all.
#>
param(
    [int]$Workers = [Math]::Max(1, [Environment]::ProcessorCount - 2),
    [ValidateSet("all","train","roster","play","screen","export")]
    [string]$Phase = "all",
    [int]$GamesPerPair = 16,
    [int]$N = 45,
    [int]$SweepSeed = 8917,
    [int]$OnlyDraws = 0,
    [string]$ScreenStore = "ranking/matches_screen_gzarch.jsonl",
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"
$Root       = Split-Path -Parent $PSScriptRoot
$TrainExe   = Join-Path $Root "train.exe"
$RankExe    = Join-Path $Root "rank.exe"
$SweepDir   = Join-Path $Root "models\sweep"
$Ledger     = Join-Path $SweepDir "gumbelzero_arch_study.csv"
$RosterOut  = Join-Path $Root "ranking\roster_gumbelzero_arch.txt"
$CohortOut  = Join-Path $Root "ranking\cohort_gumbelzero_arch.txt"
$BaseRoster = Join-Path $Root "ranking\roster_screening_pool.txt"
$Standings  = Join-Path $Root "ranking\standings.tsv"
$PinnedStandings = Join-Path $Root "ranking\standings_screen_gzarch_pinned.tsv"
$ResultsOut = Join-Path $Root "plans\gumbel-mcts-arch-sweep-agents-6-silver-thistle.tsv"
$ResultsWideOut = Join-Path $Root "plans\gumbel-mcts-arch-sweep-agents-6-silver-thistle.wide.tsv"

# Shared across EVERY draw (the consistency rule): no draw gets finer or
# coarser resolution than another.
$SharedRungs = 100,400,1500,4000

# ---- Draw list: single source of truth is Get-GumbelZeroArchDraws ----
. (Join-Path $PSScriptRoot "gumbelzero_arch_sample.ps1")
$Draws = @(Get-GumbelZeroArchDraws -N $N -SweepSeed $SweepSeed)
if ($OnlyDraws -gt 0) { $Draws = @($Draws | Select-Object -First $OnlyDraws) }

# ---- Expand draws x seeds into training-run cells ----
# Slots 1402.. -- results-5's joint sweep owns 998..1401 (src/CLAUDE.md's
# slot ledger); cross-checked against .gitignore's slot exception list
# (highest exception-listed number 707) and the locally trained slot files
# (highest 1401) before claiming this range, per the ledger's own warning.
$Cells = @()
$slot = 1402
foreach ($row in $Draws) {
    $seed = switch -Wildcard ($row.Draw) {
        "REF_MLP"  { 8901 }
        "REF_CONV" { 8902 }
        "M*"       { 8910 + [int]($row.Draw.Substring(1)) }
        "C*"       { 8960 + [int]($row.Draw.Substring(1)) }
    }
    $c = [ordered]@{
        Block = $row.Draw; Seed = $seed; Rungs = $SharedRungs
        ModelType = $row.ModelType; Arch = $row.Arch
        Sims = [int]$row.Sims; Lr = $row.Lr; L2 = $row.L2
        ReplayCap = [int]$row.ReplayCap; ReplayWarm = [int]$row.ReplayWarm
        Batch = [int]$row.Batch; Open = [int]$row.Open
        Cvisit = [int]$row.Cvisit; Cscale = [int]$row.Cscale; M = [int]$row.M
    }
    $c.Slots = @()
    foreach ($r in $SharedRungs) { $c.Slots += $script:slot; $script:slot++ }
    $Cells += [PSCustomObject]$c
}

$totalAgents = ($Cells | ForEach-Object { $_.Slots.Count } | Measure-Object -Sum).Sum
Write-Host "Gumbel-Zero architecture sweep: $($Draws.Count) draws (seed $SweepSeed) -> $($Cells.Count) training runs -> $totalAgents cohort agents (slots 1402..$($slot-1))"

if (-not (Test-Path $SweepDir)) { New-Item -ItemType Directory -Path $SweepDir | Out-Null }
if (-not (Test-Path $Ledger)) {
    "block,seed,modeltype,arch,sims,lr,l2,replaycap,replaywarm,batch,open,cvisit,cscale,m,rung,slot,model" |
        Out-File -FilePath $Ledger -Encoding ascii
}
$done = @{}
Import-Csv $Ledger | ForEach-Object { $done["$($_.block)|$($_.seed)|$($_.rung)"] = $_ }

# ---- Phase: train ----
function RunTraining {
    $jobs = @()
    foreach ($c in $Cells) {
        $key = "$($c.Block)|$($c.Seed)|$($c.Rungs[-1])"
        if ($done.ContainsKey($key)) { Write-Host "  [skip] $($c.Block) seed $($c.Seed) already trained"; continue }
        $out = "models/sweep/gza_$($c.Block)_s$($c.Seed)"
        $a = @("gumbelzero", "--out", $out,
               "--ckpt-at", ($c.Rungs -join ","),
               "--games", $c.Rungs[-1],
               "--sims", $c.Sims, "--lr", $c.Lr, "--l2", $c.L2,
               "--replay-capacity", $c.ReplayCap, "--replay-warmup", $c.ReplayWarm,
               "--batch-size", $c.Batch, "--open-plies", $c.Open,
               "--model-type", $c.ModelType,
               "--seed", $c.Seed, "--report-every", 0)
        if ($c.ModelType -eq "mlp")  { $a += @("--mlp-hidden", $c.Arch) }
        if ($c.ModelType -eq "conv") { $a += @("--conv-channels", $c.Arch) }
        Write-Host "  train $($c.Block) seed $($c.Seed): $($c.ModelType)($($c.Arch)) sims=$($c.Sims) lr=$($c.Lr) l2=$($c.L2) replay=$($c.ReplayCap)/$($c.ReplayWarm) batch=$($c.Batch) open=$($c.Open) | cert: cvisit=$($c.Cvisit) cscale=$($c.Cscale) m=$($c.M)"
        if ($DryRun) { continue }
        while (@($jobs | Where-Object { -not $_.HasExited }).Count -ge $Workers) { Start-Sleep -Milliseconds 400 }
        $jobs += Start-Process -FilePath $TrainExe -ArgumentList $a -PassThru -NoNewWindow `
                     -RedirectStandardOutput "$SweepDir\gza_$($c.Block)_s$($c.Seed).log"
    }
    if (-not $DryRun) {
        Write-Host "  waiting for $(@($jobs | Where-Object { -not $_.HasExited }).Count) run(s)..."
        $jobs | ForEach-Object { $_.WaitForExit() }
    }

    # Publish each rung into its own slot file and record it.
    foreach ($c in $Cells) {
        $out = "models/sweep/gza_$($c.Block)_s$($c.Seed)"
        for ($i = 0; $i -lt $c.Rungs.Count; $i++) {
            $rung = $c.Rungs[$i]; $sl = $c.Slots[$i]
            $src = Join-Path $Root "$($out)_g$rung.txt"
            $dst = Join-Path $SweepDir "slot$sl.txt"
            if (-not (Test-Path $src)) { Write-Warning "  missing rung $rung for $($c.Block) s$($c.Seed)"; continue }
            Copy-Item $src $dst -Force
            $key = "$($c.Block)|$($c.Seed)|$rung"
            if (-not $done.ContainsKey($key)) {
                # Arch (e.g. "16,16" for conv-channels, "64,32" for mlp-hidden)
                # contains embedded commas, so it must be CSV-quoted -- an
                # unquoted comma here silently shifts every later column
                # (rung/slot/model) on Import-Csv re-read, which breaks both
                # $done resumability and export_cohort_results.ps1's join.
                "$($c.Block),$($c.Seed),$($c.ModelType),`"$($c.Arch)`",$($c.Sims),$($c.Lr),$($c.L2),$($c.ReplayCap),$($c.ReplayWarm),$($c.Batch),$($c.Open),$($c.Cvisit),$($c.Cscale),$($c.M),$rung,$sl,$dst" |
                    Add-Content -Path $Ledger -Encoding Ascii
            }
        }
    }
}

# ---- Phase: roster ----
# Writes roster_gumbelzero_arch.txt (roster_screening_pool.txt plus the
# cohort) and cohort_gumbelzero_arch.txt (the id list --cohort reads). Each
# cohort agent is rated under gaz(sims=N,cvisit=C,cscale=S,m=M)@1 with
# N/C/S/M = the SAME values drawn for its training block. The mlp/conv
# architecture itself needs no separate encoding here -- learned()'s
# canonical descriptor (archDescForSlot) reads it straight off the slot
# file's own type=/v_type= header, so `rank.exe canon` fills it in below.
function BuildRoster {
    $hashes = @{}
    & $RankExe check 2>&1 | Select-String 'models/sweep/slot(\d+)\.txt = ([0-9a-f]{8})' | ForEach-Object {
        $hashes[[int]$_.Matches[0].Groups[1].Value] = $_.Matches[0].Groups[2].Value
    }
    $lines = @(); $ids = @()
    foreach ($c in $Cells) {
        for ($i = 0; $i -lt $c.Rungs.Count; $i++) {
            $sl = $c.Slots[$i]
            if (-not $hashes.ContainsKey($sl)) { Write-Warning "  no hash for slot $sl (not trained?)"; continue }
            $id = "gaz(sims=$($c.Sims),cvisit=$($c.Cvisit),cscale=$($c.Cscale),m=$($c.M))@1.learned(s$sl,$($hashes[$sl]))@1"
            $lines += "on $id"; $ids += $id
        }
    }
    $marker = "# ---- Gumbel-Zero architecture sweep cohort ($($ids.Count) agents), added $(Get-Date -Format yyyy-MM-dd) ----"
    Get-Content $BaseRoster | Out-File -FilePath $RosterOut -Encoding ascii
    "" | Add-Content -Path $RosterOut -Encoding ascii
    $marker | Add-Content -Path $RosterOut -Encoding ascii
    $lines | Add-Content -Path $RosterOut -Encoding ascii

    $canonLines = & $RankExe canon --roster $RosterOut
    $canonLines | Out-File -FilePath $RosterOut -Encoding ascii

    $afterMarker = $false
    $canonLines | ForEach-Object {
        if ($_ -eq $marker) { $script:afterMarker = $true; return }
        if ($script:afterMarker -and $_ -match '^on\s+(\S.*)$') { $Matches[1] }
    } | Out-File -FilePath $CohortOut -Encoding ascii

    Write-Host "  roster -> $RosterOut ($($ids.Count) cohort agents appended, base = $BaseRoster)"
    Write-Host "  cohort -> $CohortOut"
    & $RankExe check --roster $RosterOut 2>&1 | Select-String -NotMatch '^model hash' | Select-Object -Last 4
}

# ---- Phase: play ----
# Pool-only gauntlet games (rank.exe gauntlet), NOT play --cohort -- same
# rationale as results-5 (gumbelzero_joint_study.ps1): a pinned cohort play
# also schedules cohort-vs-cohort games, quadratic in cohort size, and this
# cohort is comparable in size to results-5's 404-checkpoint cohort.
#
# Workers run in PARALLEL PROCESSES, each writing its OWN shard store file
# (never multiple processes appending one shared file), merged into
# $ScreenStore only after every worker exits cleanly.
function PlayCohort {
    $ids = Get-Content $CohortOut | Where-Object { $_.Trim() -ne "" }
    Write-Host "  gauntlet-playing $($ids.Count) checkpoints at $GamesPerPair games/opponent vs roster_screening_pool.txt, $Workers shards"
    Write-Host "  store: $ScreenStore (screening pool, NOT the permanent ladder)"

    $shardFiles = @()
    $buckets = New-Object 'System.Collections.Generic.List[System.Collections.Generic.List[string]]'
    for ($w = 0; $w -lt $Workers; $w++) { $buckets.Add((New-Object 'System.Collections.Generic.List[string]')) }
    for ($i = 0; $i -lt $ids.Count; $i++) { $buckets[$i % $Workers].Add($ids[$i]) }

    $jobs = @()
    for ($w = 0; $w -lt $Workers; $w++) {
        if ($buckets[$w].Count -eq 0) { continue }
        $shardStore = "$ScreenStore.$w"
        $shardFiles += $shardStore
        $bat = Join-Path $SweepDir "gza_play_worker$w.bat"
        $lines = @("@echo off")
        foreach ($id in $buckets[$w]) {
            $lines += "`"$RankExe`" gauntlet --roster `"$BaseRoster`" --in `"$shardStore`" --id `"$id`" --games $GamesPerPair --keep"
            $lines += "if errorlevel 1 exit /b 1"
        }
        $lines += "exit /b 0"
        $lines | Out-File -FilePath $bat -Encoding ascii
        if ($DryRun) { continue }
        $p = Start-Process -FilePath "cmd.exe" -ArgumentList "/c", "`"$bat`"" -PassThru -NoNewWindow `
                 -RedirectStandardOutput "$SweepDir\gza_play_worker$w.log"
        [void]$p.Handle
        $jobs += $p
    }
    if (-not $DryRun) {
        Write-Host "  waiting for $($jobs.Count) shard(s)..."
        $jobs | ForEach-Object { $_.WaitForExit() }
        $bad = $jobs | Where-Object { $_.ExitCode -ne 0 }
        if ($bad) { throw "  $($bad.Count) gauntlet shard(s) exited non-zero; store NOT merged, inspect gza_play_worker*.log" }
        foreach ($sf in $shardFiles) {
            if (Test-Path $sf) {
                Get-Content $sf | Add-Content -Path $ScreenStore -Encoding Ascii
                Remove-Item $sf -Force
            }
        }
        Write-Host "  merged $($shardFiles.Count) shard(s) -> $ScreenStore"
    }
}

# ---- Phase: screen ----
function ScreenCohort {
    Write-Host "  pinned fit over $ScreenStore (screening pool frozen at ranking/standings.tsv)"
    & $RankExe rate --roster $RosterOut --in $ScreenStore --pin $Standings
    Write-Host ""
    Write-Host "Cohort results are in ranking/standings_screen_gzarch_pinned.tsv (canonical files untouched)."
    Write-Host "CERTIFICATION is a separate, deliberate step, not run by this script."
}

# ---- Phase: export ----
function ExportResults {
    $notes = @(
        "Gumbel-Zero mlp/conv architecture sweep, follow-up round to plans/gumbel-mcts-results-5-violet-harbor.md (linear only). One row per checkpoint.",
        "modeltype/arch columns are the drawn --model-type and --mlp-hidden (mlp)/--conv-channels (conv) values. conv's own FC head (--mlp-hidden) is fixed empty this round, not swept.",
        "cvisit/cscale/m columns are RATING-time search shape only (the gaz(...) serving head). Training self-play never reads them, same as results-5.",
        "elo/games/cpu_ms_move/playstyle columns are from a PINNED screening fit against ranking/roster_screening_pool.txt (Docs/ranking-workflow.md Workflow A):",
        "screening only, not certification."
    )
    & (Join-Path $PSScriptRoot "export_cohort_results.ps1") `
        -Ledger $Ledger `
        -PinnedStandings $PinnedStandings `
        -Out $ResultsOut `
        -HeaderComment $notes `
        -GroupBy block,seed -WideBy rung -WideOut $ResultsWideOut
}

switch ($Phase) {
    "train"  { RunTraining }
    "roster" { BuildRoster }
    "play"   { PlayCohort }
    "screen" { ScreenCohort }
    "export" { ExportResults }
    "all"    { RunTraining; BuildRoster; PlayCohort; ScreenCohort; ExportResults }
}
