<#
.SYNOPSIS
  Gumbel-Zero Pass 2: random-search sweep over the self-play trainer's
  hyperparameter space, trained, played into the existing roster, and rated
  on a FROZEN scale.

.DESCRIPTION
  Draw list is generated by tools/gumbelzero_sample_pass2.ps1's
  Get-GumbelZeroPass2Draws (dot-sourced below), the single source of truth
  for the sampling -- this script never re-implements it, so what trains can
  never drift from what was reviewed via `tools\gumbelzero_sample_pass2.ps1`
  before any compute was spent. Random search (Bergstra & Bengio 2012,
  Docs/works-cited.md), not one-axis-at-a-time. See
  Docs/model-training-playbook.md.

  Round A only: 1 seed per draw, 3 shared rungs (100/400/1500 games) so every
  arm gets checkpointed at the SAME points and an interior optimum can't be
  missed by screening at only one rung (the mistake TD-Leaf's Pass 2 Round A
  made -- see plans/tdleaf-results-2-amber-pangolin.md's post-peak-screening
  caveat). Round B (top 8 draws x 2 more seeds) is a separate, later
  invocation once Round A's results have been reviewed with the developer,
  matching TD-Leaf's own two-stage design.

  Each draw's `sims` value is used for BOTH the self-play generator and the
  `gaz(sims=N)@1` head its checkpoints are rated under -- see
  gumbelzero_sample_pass2.ps1's header for why.

  Rating is deliberately two-stage, same as the TD-Leaf study:
    SCREEN  rank.exe rate --pin ranking/standings.tsv
            The existing roster is held at its current Elo and only the
            cohort is solved. Cannot dethrone anything (ratings are inputs).
    CERTIFY A plain unpinned refit, run deliberately as the LAST step once the
            agents to keep have been chosen (ranking/CHAMPION.md rule 1). Not
            run by this script.

  Screening pool (-ScreenStore): cohort games go to their own store, never
  the permanent ladder -- see tools/tdleaf_study.ps1's header for the full
  rationale (a screening cohort is mostly candidates that get discarded, and
  --cohort tops up every cohort-vs-roster pair too).

.PARAMETER Workers
  Parallel training processes, and shards for the play phase.

.PARAMETER Phase
  all | train | roster | play | screen. Phases are resumable and idempotent.

.PARAMETER GamesPerPair
  Games per pair for the play phase. 8 is screening level.

.PARAMETER N
  Number of random draws (plus 1 fixed reference configuration). Must match
  what was reviewed via gumbelzero_sample_pass2.ps1.

.PARAMETER SweepSeed
  Seed for the random draw. Default 77, reviewed via
  gumbelzero_sample_pass2.ps1 before this script ran.
#>
param(
    [int]$Workers = 12,
    [ValidateSet("all","train","roster","play","screen")]
    [string]$Phase = "all",
    [int]$GamesPerPair = 8,
    [int]$N = 20,
    [int]$SweepSeed = 77,
    [string]$ScreenStore = "ranking/matches_screen_gz.jsonl",
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"
$Root      = Split-Path -Parent $PSScriptRoot
$TrainExe  = Join-Path $Root "train.exe"
$RankExe   = Join-Path $Root "rank.exe"
$SweepDir  = Join-Path $Root "models\sweep"
$Ledger    = Join-Path $SweepDir "gumbelzero_pass2_study.csv"
$RosterOut = Join-Path $Root "ranking\roster_gumbelzero_pass2.txt"
$CohortOut = Join-Path $Root "ranking\cohort_gumbelzero_pass2.txt"
$BaseRoster= Join-Path $Root "ranking\roster.txt"
$Standings = Join-Path $Root "ranking\standings.tsv"

# Shared across EVERY draw (the consistency rule): no draw gets finer or
# coarser resolution than another.
$SharedRungs = 100,400,1500

# ---- Draw list: single source of truth is Get-GumbelZeroPass2Draws ----
. (Join-Path $PSScriptRoot "gumbelzero_sample_pass2.ps1")
$Draws = Get-GumbelZeroPass2Draws -N $N -SweepSeed $SweepSeed

# ---- Expand draws x seeds into training-run cells ----
# Slots 660.. (Pass 1 owns 650..659; see src/CLAUDE.md's slotFile() note).
$Cells = @()
$slot = 660
foreach ($row in $Draws) {
    $seed = if ($row.Draw -eq "REF") { 2101 } else { 2100 + [int]($row.Draw.Substring(1)) }
    $c = [ordered]@{
        Block = $row.Draw; Seed = $seed; Rungs = $SharedRungs
        Sims = [int]$row.Sims; Lr = $row.Lr; L2 = $row.L2
        ReplayCap = [int]$row.ReplayCap; ReplayWarm = [int]$row.ReplayWarm
        Batch = [int]$row.Batch; Open = [int]$row.Open
    }
    $c.Slots = @()
    foreach ($r in $SharedRungs) { $c.Slots += $script:slot; $script:slot++ }
    $Cells += [PSCustomObject]$c
}

$totalAgents = ($Cells | ForEach-Object { $_.Slots.Count } | Measure-Object -Sum).Sum
Write-Host "Gumbel-Zero Pass 2 (Round A): $($Draws.Count) draws (1 ref + $N random, seed $SweepSeed) -> $($Cells.Count) training runs -> $totalAgents cohort agents (slots 660..$($slot-1))"

if (-not (Test-Path $SweepDir)) { New-Item -ItemType Directory -Path $SweepDir | Out-Null }
if (-not (Test-Path $Ledger)) {
    "block,seed,sims,lr,l2,replaycap,replaywarm,batch,open,rung,slot,model" |
        Out-File -FilePath $Ledger -Encoding ascii
}
$done = @{}
Import-Csv $Ledger | ForEach-Object { $done["$($_.block)|$($_.seed)|$($_.rung)"] = $_ }

# ---- Phase: train ----
function RunTraining {
    $jobs = @()
    foreach ($c in $Cells) {
        $key = "$($c.Block)|$($c.Seed)|$($c.Rungs[-1])"
        if ($done.ContainsKey($key)) { Write-Host "  [skip] $($c.Block) seed $($c.Seed) already trained"; continue }
        $out = "models/sweep/gz2_$($c.Block)_s$($c.Seed)"
        $a = @("gumbelzero", "--out", $out,
               "--ckpt-at", ($c.Rungs -join ","),
               "--games", $c.Rungs[-1],
               "--sims", $c.Sims, "--lr", $c.Lr, "--l2", $c.L2,
               "--replay-capacity", $c.ReplayCap, "--replay-warmup", $c.ReplayWarm,
               "--batch-size", $c.Batch, "--open-plies", $c.Open,
               "--seed", $c.Seed, "--report-every", 0)
        Write-Host "  train $($c.Block) seed $($c.Seed): sims=$($c.Sims) lr=$($c.Lr) l2=$($c.L2) replay=$($c.ReplayCap)/$($c.ReplayWarm) batch=$($c.Batch) open=$($c.Open)"
        if ($DryRun) { continue }
        while (@($jobs | Where-Object { -not $_.HasExited }).Count -ge $Workers) { Start-Sleep -Milliseconds 400 }
        $jobs += Start-Process -FilePath $TrainExe -ArgumentList $a -PassThru -NoNewWindow `
                     -RedirectStandardOutput "$SweepDir\gz2_$($c.Block)_s$($c.Seed).log"
    }
    if (-not $DryRun) {
        Write-Host "  waiting for $(@($jobs | Where-Object { -not $_.HasExited }).Count) run(s)..."
        $jobs | ForEach-Object { $_.WaitForExit() }
    }

    # Publish each rung into its own slot file and record it.
    foreach ($c in $Cells) {
        $out = "models/sweep/gz2_$($c.Block)_s$($c.Seed)"
        for ($i = 0; $i -lt $c.Rungs.Count; $i++) {
            $rung = $c.Rungs[$i]; $sl = $c.Slots[$i]
            $src = Join-Path $Root "$($out)_g$rung.txt"
            $dst = Join-Path $SweepDir "slot$sl.txt"
            if (-not (Test-Path $src)) { Write-Warning "  missing rung $rung for $($c.Block) s$($c.Seed)"; continue }
            Copy-Item $src $dst -Force
            $key = "$($c.Block)|$($c.Seed)|$rung"
            if (-not $done.ContainsKey($key)) {
                "$($c.Block),$($c.Seed),$($c.Sims),$($c.Lr),$($c.L2),$($c.ReplayCap),$($c.ReplayWarm),$($c.Batch),$($c.Open),$rung,$sl,$dst" |
                    Add-Content -Path $Ledger -Encoding Ascii
            }
        }
    }
}

# ---- Phase: roster ----
# Writes roster_gumbelzero_pass2.txt (the base roster plus the cohort) and
# cohort_gumbelzero_pass2.txt (the id list --cohort reads). Each cohort agent
# is rated under gaz(sims=N)@1 with N = the SAME sims value it was trained
# with (see gumbelzero_sample_pass2.ps1's header).
function BuildRoster {
    $hashes = @{}
    & $RankExe check 2>&1 | Select-String 'models/sweep/slot(\d+)\.txt = ([0-9a-f]{8})' | ForEach-Object {
        $hashes[[int]$_.Matches[0].Groups[1].Value] = $_.Matches[0].Groups[2].Value
    }
    $lines = @(); $ids = @()
    foreach ($c in $Cells) {
        for ($i = 0; $i -lt $c.Rungs.Count; $i++) {
            $sl = $c.Slots[$i]
            if (-not $hashes.ContainsKey($sl)) { Write-Warning "  no hash for slot $sl (not trained?)"; continue }
            $id = "gaz(sims=$($c.Sims))@1.learned(s$sl,$($hashes[$sl]))@1"
            $lines += "on $id"; $ids += $id
        }
    }
    Get-Content $BaseRoster | Out-File -FilePath $RosterOut -Encoding ascii
    "" | Add-Content -Path $RosterOut -Encoding ascii
    "# ---- Gumbel-Zero Pass 2 Round A cohort ($($ids.Count) agents), added $(Get-Date -Format yyyy-MM-dd) ----" |
        Add-Content -Path $RosterOut -Encoding ascii
    $lines | Add-Content -Path $RosterOut -Encoding ascii
    $ids   | Out-File -FilePath $CohortOut -Encoding ascii
    Write-Host "  roster -> $RosterOut ($($ids.Count) cohort agents appended)"
    Write-Host "  cohort -> $CohortOut"
    & $RankExe check --roster $RosterOut 2>&1 | Select-String -NotMatch '^model hash' | Select-Object -Last 4
}

# ---- Phase: play ----
function PlayCohort {
    Write-Host "  playing cohort at $GamesPerPair games/pair, $Workers shards (cohort-filtered)"
    Write-Host "  store: $ScreenStore (screening pool, NOT the permanent ladder)"
    # -NoRate is REQUIRED -- see tools/tdleaf_study.ps1's header for the
    # 2026-07-29 incident this prevents.
    & (Join-Path $PSScriptRoot "run_rank.ps1") -Workers $Workers -Store $ScreenStore -NoRate play `
        --roster $RosterOut --cohort $CohortOut --games $GamesPerPair
}

# ---- Phase: screen ----
function ScreenCohort {
    Write-Host "  pinned fit over $ScreenStore (roster frozen at ranking/standings.tsv)"
    & $RankExe rate --roster $RosterOut --in $ScreenStore --pin $Standings
    Write-Host ""
    Write-Host "Cohort results are in ranking/standings_screen_gz_pinned.tsv (canonical files untouched)."
    Write-Host "CERTIFICATION is a separate, deliberate step, not run by this script."
}

switch ($Phase) {
    "train"  { RunTraining }
    "roster" { BuildRoster }
    "play"   { PlayCohort }
    "screen" { ScreenCohort }
    "all"    { RunTraining; BuildRoster; PlayCohort; ScreenCohort }
}
