<#
.SYNOPSIS
  TD-Leaf(lambda) Pass 2: random-search sweep over the joint hyperparameter
  space, trained, played into the existing roster, and rated on a FROZEN scale.

.DESCRIPTION
  Draw list is generated by tools/tdleaf_sample_pass2.ps1's Get-TDLeafPass2Draws
  (dot-sourced below), the single source of truth for the sampling -- this
  script never re-implements it, so what trains can never drift from what was
  reviewed via `tools\tdleaf_sample_pass2.ps1` before any compute was spent.
  Random search (Bergstra & Bengio 2012, Docs/works-cited.md), not
  one-axis-at-a-time: every draw samples every axis independently and
  simultaneously. See Docs/model-training-playbook.md.

  The game count is NOT an input. Every draw's training run writes checkpoints
  on the SAME game-count ladder (--ckpt-at) and every rung is rated as its own
  agent, so the learning curve is an output, and every draw is comparable to
  every other at the same rungs (no arm gets finer resolution than another).

  Rating is deliberately two-stage:
    SCREEN  rank.exe rate --pin ranking/standings.tsv
            The existing roster is held at its current Elo and only the
            cohort is solved. The reference scale cannot drift mid-study, and
            the fit uses cohort-vs-cohort games too, so the cohort's internal
            order is resolved -- which per-candidate gauntlets cannot do.
            A pinned fit can NEVER dethrone a champion: their ratings are
            inputs to it.
    CERTIFY A plain unpinned refit, run deliberately as the LAST step once the
            agents to keep have been chosen (ranking/CHAMPION.md rule 1). Only
            this can reorder the table or dethrone anything. Not run by this
            script.

  Screening pool (-ScreenStore, added 2026-08-01). Cohort games go to their own
  store, never the permanent ladder. A screening cohort is mostly candidates
  that will be discarded, and `--cohort` tops up every cohort-vs-roster pair, so
  writing them to the shared store floods it with games against agents nobody
  will keep: the Pass-2 run left 457,611 such rows, 71% of the whole store, and
  some rostered agents ended up with 60% of their games against candidates that
  were thrown away. Removing them afterwards is not free either, because a
  Bradley-Terry fit is joint -- those games were evidence about the ROSTERED
  agent too, so dropping them moved 153 of 170 rostered agents. Keeping them out
  from the start avoids both problems. On promotion, `rank.exe split` over the
  screening store separates the kept agents' games for merging into the ladder.
  Full analysis: plans/store-sharding-results-1-tidy-albatross.md.

.PARAMETER Workers
  Parallel training processes, and shards for the play phase.

.PARAMETER Phase
  all | train | roster | play | screen. Phases are resumable and idempotent.

.PARAMETER GamesPerPair
  Games per pair for the play phase. 8 is screening level; 32 is the project's
  certification standard (ranking/CHAMPION.md rule 2).

.PARAMETER N
  Number of random draws (plus 1 fixed reference configuration). Must match
  what was reviewed via tdleaf_sample_pass2.ps1 -- confirmed at 24, 2026-07-30.

.PARAMETER SweepSeed
  Seed for the random draw. Confirmed at 42 (the default), 2026-07-30 -- the
  resulting draw's feature-version skew (7-vs-2 toward v1 among scratch-init
  draws) was reviewed and deliberately accepted rather than re-rolled.
#>
param(
    [int]$Workers = 12,
    [ValidateSet("all","train","roster","play","screen")]
    [string]$Phase = "all",
    [int]$GamesPerPair = 8,
    [int]$N = 24,
    [int]$SweepSeed = 42,
    # Screening games go to their OWN store, never the permanent ladder. See
    # the "Screening pool" note in the .DESCRIPTION above.
    [string]$ScreenStore = "ranking/matches_screen.jsonl",
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"
$Root      = Split-Path -Parent $PSScriptRoot
$TrainExe  = Join-Path $Root "train.exe"
$RankExe   = Join-Path $Root "rank.exe"
$SweepDir  = Join-Path $Root "models\sweep"
$Ledger    = Join-Path $SweepDir "tdleaf_pass2_study.csv"
$RosterOut = Join-Path $Root "ranking\roster_tdleaf_pass2.txt"
$CohortOut = Join-Path $Root "ranking\cohort_tdleaf_pass2.txt"
$BaseRoster= Join-Path $Root "ranking\roster.txt"
$Standings = Join-Path $Root "ranking\standings.tsv"

# The evaluator wrapper every cohort agent is rated at. ONE head for the whole
# cohort (ranking/CHAMPION.md rule 6): mixing heads is not an evaluator comparison.
$Wrapper = "ab(d6,tt,ord,nb200k)@1"

# Shared across EVERY draw (the consistency rule): no draw gets finer or
# coarser resolution than another.
$SharedRungs = 250,500,1000,1500,2500,4000

# ---- Draw list: single source of truth is Get-TDLeafPass2Draws ----
. (Join-Path $PSScriptRoot "tdleaf_sample_pass2.ps1")
$Draws = Get-TDLeafPass2Draws -N $N -SweepSeed $SweepSeed

# ---- Expand draws x seeds into training-run cells ----
# Slots 166.. (round 1 owns 128..165; the ML_SLOTS 256 -> 1024 raise on
# 2026-07-30 opened this range -- see src/CLAUDE.md's slotFile() note).
$Cells = @()
$slot = 166
foreach ($row in $Draws) {
    $seeds = if ($row.Draw -eq "REF") {
        1001,2002,3003,4004,5005,6006
    } else {
        $i = [int]($row.Draw.Substring(1))          # "R7" -> 7
        1..([int]$row.Seeds) | ForEach-Object { $i * 100 + $_ }   # R7 -> 701,702,703
    }
    $lrOn = ($row.LrSched -eq "on")
    $exOn = ($row.ExploreSched -eq "on")
    foreach ($seed in $seeds) {
        $c = [ordered]@{
            Block = $row.Draw; Seed = $seed; Rungs = $SharedRungs
            Lambda = $row.Lambda; Lr = $row.Lr
            LrFloor = if ($lrOn) { [math]::Round($row.Lr / 10, 6) } else { $row.Lr }
            LrDecayGames = if ($lrOn) { 2000 } else { 0 }
            L2 = $row.L2
            Explore = $row.Explore
            ExploreFloor = if ($exOn) { 0.0 } else { $row.Explore }
            ExploreDecayGames = if ($exOn) { 2000 } else { 0 }
            Init = if ($row.Init -eq "champion") { "models/pst_value.txt" } else { "" }
            Depth = if ($row.Depth -eq "d4") { 4 } else { 6 }
            NodeBudget = if ($row.Depth -eq "d4") { 0 } else { 200000 }
            OpenPlies = [int]$row.OpenPlies
            ModelType = if ($row.Arch -eq "linear") { "linear" } else { "mlp" }
            MlpHidden = switch ($row.Arch) { "mlp16" { "16" } "mlp32" { "32" } default { "" } }
            FeatVer = [int]$row.FeatVer
        }
        $c.Slots = @()
        foreach ($r in $SharedRungs) { $c.Slots += $script:slot; $script:slot++ }
        $Cells += [PSCustomObject]$c
    }
}

$totalAgents = ($Cells | ForEach-Object { $_.Slots.Count } | Measure-Object -Sum).Sum
Write-Host "TD-Leaf Pass 2: $($Draws.Count) draws (1 ref + $N random, seed $SweepSeed) -> $($Cells.Count) training runs -> $totalAgents cohort agents (slots 166..$($slot-1))"

if (-not (Test-Path $SweepDir)) { New-Item -ItemType Directory -Path $SweepDir | Out-Null }
if (-not (Test-Path $Ledger)) {
    "block,seed,lambda,lr,lrfloor,lrdecaygames,l2,explore,explorefloor,exploredecaygames,depth,nodebudget,openplies,init,modeltype,mlphidden,featver,rung,slot,model" |
        Out-File -FilePath $Ledger -Encoding ascii
}
$done = @{}
Import-Csv $Ledger | ForEach-Object { $done["$($_.block)|$($_.seed)|$($_.rung)"] = $_ }

# ---- Phase: train ----
function RunTraining {
    $jobs = @()
    foreach ($c in $Cells) {
        $key = "$($c.Block)|$($c.Seed)|$($c.Rungs[-1])"
        if ($done.ContainsKey($key)) { Write-Host "  [skip] $($c.Block) seed $($c.Seed) already trained"; continue }
        $out = "models/sweep/tdl2_$($c.Block)_s$($c.Seed)"
        $a = @("tdleaf", "--out", $out,
               "--ckpt-at", ($c.Rungs -join ","),
               "--games", $c.Rungs[-1],
               "--depth", $c.Depth, "--node-budget", $c.NodeBudget,
               "--lambda", $c.Lambda, "--lr", $c.Lr,
               "--lr-floor", $c.LrFloor, "--lr-decay-games", $c.LrDecayGames,
               "--l2", $c.L2,
               "--explore", $c.Explore,
               "--explore-floor", $c.ExploreFloor, "--explore-decay-games", $c.ExploreDecayGames,
               "--open-plies", $c.OpenPlies, "--seed", $c.Seed,
               "--feature-version", $c.FeatVer,
               "--model-type", $c.ModelType,
               "--report-every", 0)
        if ($c.Init -ne "") { $a += @("--init", $c.Init) }
        if ($c.ModelType -eq "mlp") { $a += @("--mlp-hidden", $c.MlpHidden) }
        Write-Host "  train $($c.Block) seed $($c.Seed): lambda=$($c.Lambda) lr=$($c.Lr)(->$($c.LrFloor)/$($c.LrDecayGames)g) l2=$($c.L2) explore=$($c.Explore)(->$($c.ExploreFloor)/$($c.ExploreDecayGames)g) d$($c.Depth) $($c.ModelType)$($c.MlpHidden) fv$($c.FeatVer) init=$(if($c.Init){'champ'}else{'scratch'})"
        if ($DryRun) { continue }
        while (@($jobs | Where-Object { -not $_.HasExited }).Count -ge $Workers) { Start-Sleep -Milliseconds 400 }
        $jobs += Start-Process -FilePath $TrainExe -ArgumentList $a -PassThru -NoNewWindow `
                     -RedirectStandardOutput "$SweepDir\tdl2_$($c.Block)_s$($c.Seed).log"
    }
    if (-not $DryRun) {
        Write-Host "  waiting for $(@($jobs | Where-Object { -not $_.HasExited }).Count) run(s)..."
        $jobs | ForEach-Object { $_.WaitForExit() }
    }

    # Publish each rung into its own slot file and record it.
    foreach ($c in $Cells) {
        $out = "models/sweep/tdl2_$($c.Block)_s$($c.Seed)"
        for ($i = 0; $i -lt $c.Rungs.Count; $i++) {
            $rung = $c.Rungs[$i]; $sl = $c.Slots[$i]
            $src = Join-Path $Root "$($out)_g$rung.txt"
            $dst = Join-Path $SweepDir "slot$sl.txt"
            if (-not (Test-Path $src)) { Write-Warning "  missing rung $rung for $($c.Block) s$($c.Seed)"; continue }
            Copy-Item $src $dst -Force
            $key = "$($c.Block)|$($c.Seed)|$rung"
            if (-not $done.ContainsKey($key)) {
                "$($c.Block),$($c.Seed),$($c.Lambda),$($c.Lr),$($c.LrFloor),$($c.LrDecayGames),$($c.L2),$($c.Explore),$($c.ExploreFloor),$($c.ExploreDecayGames),$($c.Depth),$($c.NodeBudget),$($c.OpenPlies),$($c.Init),$($c.ModelType),$($c.MlpHidden),$($c.FeatVer),$rung,$sl,$dst" |
                    Add-Content -Path $Ledger -Encoding Ascii
            }
        }
    }
}

# ---- Phase: roster ----
# Writes roster_tdleaf_pass2.txt (the base roster plus the cohort) and
# cohort_tdleaf_pass2.txt (the id list --cohort reads).
function BuildRoster {
    $hashes = @{}
    & $RankExe check 2>&1 | Select-String 'models/sweep/slot(\d+)\.txt = ([0-9a-f]{8})' | ForEach-Object {
        $hashes[[int]$_.Matches[0].Groups[1].Value] = $_.Matches[0].Groups[2].Value
    }
    # Legacy short-form id (slot, hash only) -- NOT the hand-computed rich form. A
    # rich-form claim (architecture/feature-count) can be WRONG when the config's
    # claimed --model-type/--feature-version was silently overridden by --init, as
    # a real sanity run caught 2026-07-30 (champion-init + --model-type mlp trained
    # linear; the wrong rich-form id was rejected by `rank.exe check`, not silently
    # accepted). The legacy form makes no claim to be wrong: rank.exe's own
    # parser fills the descriptive fields in from the ACTUAL slot file (see
    # learnedSpellingOnly / rankUpgradeId in src/ranking.cpp), so the id can
    # never mismatch the model it names.
    $lines = @(); $ids = @()
    foreach ($c in $Cells) {
        for ($i = 0; $i -lt $c.Rungs.Count; $i++) {
            $sl = $c.Slots[$i]
            if (-not $hashes.ContainsKey($sl)) { Write-Warning "  no hash for slot $sl (not trained?)"; continue }
            $id = "$Wrapper.learned(s$sl,$($hashes[$sl]))@1"
            $lines += "on $id"; $ids += $id
        }
    }
    Get-Content $BaseRoster | Out-File -FilePath $RosterOut -Encoding ascii
    "" | Add-Content -Path $RosterOut -Encoding ascii
    "# ---- TD-Leaf Pass 2 cohort ($($ids.Count) agents), added $(Get-Date -Format yyyy-MM-dd) ----" |
        Add-Content -Path $RosterOut -Encoding ascii
    $lines | Add-Content -Path $RosterOut -Encoding ascii
    $ids   | Out-File -FilePath $CohortOut -Encoding ascii
    Write-Host "  roster -> $RosterOut ($($ids.Count) cohort agents appended)"
    Write-Host "  cohort -> $CohortOut"
    & $RankExe check --roster $RosterOut 2>&1 | Select-String -NotMatch '^model hash' | Select-Object -Last 4
}

# ---- Phase: play ----
function PlayCohort {
    Write-Host "  playing cohort at $GamesPerPair games/pair, $Workers shards (cohort-filtered)"
    Write-Host "  store: $ScreenStore (screening pool, NOT the permanent ladder)"
    # -NoRate is REQUIRED: run_rank.ps1 otherwise finishes with an UNPINNED rate
    # that would overwrite the canonical ranking/ratings.tsv + standings.tsv with
    # a fit including this cohort -- the exact drift `rate --pin` exists to
    # prevent. (Learned the hard way 2026-07-29; the generated files had to be
    # restored from git afterwards.)
    & (Join-Path $PSScriptRoot "run_rank.ps1") -Workers $Workers -Store $ScreenStore -NoRate play `
        --roster $RosterOut --cohort $CohortOut --games $GamesPerPair
}

# ---- Phase: screen ----
function ScreenCohort {
    Write-Host "  pinned fit over $ScreenStore (roster frozen at ranking/standings.tsv)"
    # The screening store holds cohort-vs-roster games as well as
    # cohort-vs-cohort ones, and the roster agents enter at their pinned Elo, so
    # the cohort is still placed on the canonical scale without the permanent
    # ladder ever seeing these games.
    & $RankExe rate --roster $RosterOut --in $ScreenStore --pin $Standings
    Write-Host ""
    Write-Host "Cohort results are in ranking/standings_screen_pinned.tsv (canonical files untouched)."
    Write-Host "CERTIFICATION is a separate, deliberate step:"
    Write-Host "  1. choose which cohort agents to keep and append them to ranking/roster.txt"
    Write-Host "  2. rank.exe split --in $ScreenStore   (its 'roster' bucket is exactly the games"
    Write-Host "     between agents that are NOW rostered -- the promoted ones)"
    Write-Host "  3. append that bucket to the permanent store and list it in matches.index.txt"
    Write-Host "  4. run a plain unpinned 'rank.exe rate'"
    Write-Host "Discarded candidates' games stay in the screening store and never reach the ladder."
}

switch ($Phase) {
    "train"  { RunTraining }
    "roster" { BuildRoster }
    "play"   { PlayCohort }
    "screen" { ScreenCohort }
    "all"    { RunTraining; BuildRoster; PlayCohort; ScreenCohort }
}
